# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import svhn_classifier_pb2 as svhn__classifier__pb2


class SvhnClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/SvhnClassifier/Predict',
        request_serializer=svhn__classifier__pb2.Image.SerializeToString,
        response_deserializer=svhn__classifier__pb2.Prediction.FromString,
        )


class SvhnClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SvhnClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=svhn__classifier__pb2.Image.FromString,
          response_serializer=svhn__classifier__pb2.Prediction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SvhnClassifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
